### ISSUE TITLE
大佬我部署的国外服务器一直出现，Sorry, looks like your network settings are preventing access to this feature

### ISSUE THREAD

**Issue by tutianyu101** [adams549659584/go-proxy-bingai#110]
韩国，东京，香港服务器一直会出现这个，不定时的。大佬你的甲骨文小鸡为什么没这个啊?具体提示是:Sorry, looks like your network settings are preventing access to this feature。我该怎么解决啊?

**Comment by adams549659584** [comment]
提示这个的时候，控制台有什么错误吗？不大清楚怎么回事

**Comment by tutianyu101** [comment]
> 提示这个的时候，控制台有什么错误吗？不大清楚怎么回事

有提示，就是会话id没有创建成功，然后十次后就停了，能不停吗?要多刷新几次才创建会话id成功

**Comment by tutianyu101** [comment]
> 提示这个的时候，控制台有什么错误吗？不大清楚怎么回事

理论上东京韩国这种地方不应该会话id创建不成功的啊?

**Comment by adams549659584** [comment]
看看后台的日志，有没有个 RandIP : xxx，可能重定向到CN了，发现有些美国ip也会被重定向到CN的，下次会优化下这个

**Comment by tutianyu101** [comment]
> 看看后台的日志，有没有个 RandIP : xxx，可能重定向到CN了，发现有些美国ip也会被重定向到CN的，下次会优化下这个

我今天在遇到这个，我截图给你，大佬

**Comment by tutianyu101** [comment]
> 看看后台的日志，有没有个 RandIP : xxx，可能重定向到CN了，发现有些美国ip也会被重定向到CN的，下次会优化下这个

这个下午开始就很频繁，我今天截图下

**Comment by adams549659584** [comment]
好的

**Comment by tutianyu101** [comment]
> 好的

大佬，“有没有个 RandIP : xxx”    这个在哪里看？

**Comment by adams549659584** [comment]
在后台程序的命令界面中可以看，比如 docker的话，可以用以下命令查看今天的日志
```bash
docker logs -f --since="2023-05-29" go-proxy-bingai
```

**Comment by tutianyu101** [comment]
![bing4](https://github.com/adams549659584/go-proxy-bingai/assets/134258491/c1f0f648-917c-4238-98cd-18a8e8a664fa)
大佬，我该怎么查？
![bing5](https://github.com/adams549659584/go-proxy-bingai/assets/134258491/82c1dbce-583e-431d-b303-5e400f5f8d3b)

**Comment by tutianyu101** [comment]
> 在后台程序的命令界面中可以看，比如 docker的话，可以用以下命令查看今天的日志
> 
> ```shell
> docker logs -f --since="2023-05-29" go-proxy-bingai
> ```

上面那个是韩国服务器出现的

**Comment by adams549659584** [comment]
你的有点奇怪，你的nginx 配置了什么吗？请求头似乎都没传给 微软那边，响应的居然是未压缩的js，页面响应的 cookie  randip 也不能写入网站

**Comment by adams549659584** [comment]
似乎又只是偶尔这样，奇怪

**Comment by tutianyu101** [comment]
> 似乎又只是偶尔这样，奇怪

对的，我没配置什么，都是按照页面上的教程来的
docker logs --tail=10 go-proxy-bingai >> last.log
大佬我这条输出不了日志，我该怎么处理啊？

**Comment by tutianyu101** [comment]
> 似乎又只是偶尔这样，奇怪

多刷新几次自己就好了。。我也不知道为啥，ai.cnvvg.com和bing.cnvvg.com,大佬你瞧瞧呢

**Comment by tutianyu101** [comment]
![bing7](https://github.com/adams549659584/go-proxy-bingai/assets/134258491/f3fb6f1c-3e05-4d64-af4f-fe832c8ec288)
duo多刷新几次就这样了

**Comment by tutianyu101** [comment]
![bing8](https://github.com/adams549659584/go-proxy-bingai/assets/134258491/f0727336-afae-4fe9-98fb-8329154a2098)
![bing9](https://github.com/adams549659584/go-proxy-bingai/assets/134258491/4b166c33-eb9f-444f-80b1-460cd2d0d7d4)

**Comment by tutianyu101** [comment]
> 似乎又只是偶尔这样，奇怪

大佬，又出现了，我该怎么办？

**Comment by adams549659584** [comment]
> > 似乎又只是偶尔这样，奇怪
> 
> 大佬，又出现了，我该怎么办？
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/ab262c32-fb31-4b23-88de-0dc1bfebb80f)
我也不知道怎么回事，没看出来什么问题，你可以尝试注释下这个看看还会不会出现。

**Comment by tutianyu101** [comment]
> 

大佬我还发现个问题，我按教程自建聊天室后，在cloud那边的日志发现还真的会连cn的bing

**Comment by tutianyu101** [comment]
> > > 似乎又只是偶尔这样，奇怪
> > 
> > 
> > 大佬，又出现了，我该怎么办？
> > ![image](https://user-images.githubusercontent.com/10492939/241639117-ab262c32-fb31-4b23-88de-0dc1bfebb80f.png)
> > 我也不知道怎么回事，没看出来什么问题，你可以尝试注释下这个看看还会不会出现。

大佬注释了，到现在没出现了，我在观察下

**Comment by adams549659584** [comment]
> > 
> 
> 大佬我还发现个问题，我按教程自建聊天室后，在cloud那边的日志发现还真的会连cn的bing

是会有些随机ip会被重定向到 CN，但是又是美国ip来的，不知道怎么回事

**Comment by tutianyu101** [comment]
> > > 
> > 
> > 
> > 大佬我还发现个问题，我按教程自建聊天室后，在cloud那边的日志发现还真的会连cn的bing
> 
> 是会有些随机ip会被重定向到 CN，但是又是美国ip来的，不知道怎么回事

大佬我现在在观察下，看还会不会出现无法创建会话id，我昨天联系了好几个一起部署的，都有这个问题，我找人一起试试

**Comment by tutianyu101** [comment]
> > > 
> > 
> > 
> > 大佬我还发现个问题，我按教程自建聊天室后，在cloud那边的日志发现还真的会连cn的bing
> 
> 是会有些随机ip会被重定向到 CN，但是又是美国ip来的，不知道怎么回事

大佬这个可以修复吗？

**Comment by tutianyu101** [comment]
> > > 
> > 
> > 
> > 大佬我还发现个问题，我按教程自建聊天室后，在cloud那边的日志发现还真的会连cn的bing
> 
> 是会有些随机ip会被重定向到 CN，但是又是美国ip来的，不知道怎么回事

检测到自动重新连接？我这是刷新下就好了

**Comment by tutianyu101** [comment]
> > > 似乎又只是偶尔这样，奇怪
> > 
> > 
> > 大佬，又出现了，我该怎么办？
> > ![image](https://user-images.githubusercontent.com/10492939/241639117-ab262c32-fb31-4b23-88de-0dc1bfebb80f.png)
> > 我也不知道怎么回事，没看出来什么问题，你可以尝试注释下这个看看还会不会出现。

![bing10](https://github.com/adams549659584/go-proxy-bingai/assets/134258491/8dbe4e90-d0ae-4419-aaa3-64523573bc3d)
大佬，好像还是会出现无法创建会话id，但是好像第一次重试成功，之前无论怎么重试都不成功

**Comment by tutianyu101** [comment]
算了大佬，你当我上面没说，又出现这个问题了
![bing11](https://github.com/adams549659584/go-proxy-bingai/assets/134258491/b94b3177-5837-4d56-80f6-f818b59a9d0d)

**Comment by tutianyu101** [comment]
server
{
    listen 80;
		listen 443 ssl http2;
    server_name ai.cnvvg.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/ai.cnvvg.com;

    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/ai.cnvvg.com/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/ai.cnvvg.com/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497  https://$host$request_uri;

    #SSL-END

    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END

    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-00.conf;
    #PHP-INFO-END

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/ai.cnvvg.com.conf;
    #REWRITE-END
    
        # 大佬要求加的
    include /www/wwwroot/ai.cnvvg.com/conf.global/proxy.conf;
    
    #将所有请求转发给bing_pool池的应用处理
    location / {
      proxy_pass http://127.0.0.1:8080;
      
      # 大佬要求加的
      include /www/wwwroot/ai.cnvvg.com/conf.global/proxy.conf;

      # Enable HTTP Strict Transport Security (HSTS)
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    }
    
    #配置静态资源 解决js css文件无法加载无法访问的问题，注意末尾不能有 /
    location ~ .*\.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
      proxy_pass http://127.0.0.1:8080;
      
      # 大佬要求加的
      include /www/wwwroot/ai.cnvvg.com/conf.global/proxy.conf;
      
      # Enable HTTP Strict Transport Security (HSTS)
      #add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    }
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }

    #禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }

    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null;
    }
    access_log  /www/wwwlogs/ai.cnvvg.com.log;
    error_log  /www/wwwlogs/ai.cnvvg.com.error.log;
}



这是我的nginx配置

> > > 
> > 
> > 
> > 大佬我还发现个问题，我按教程自建聊天室后，在cloud那边的日志发现还真的会连cn的bing
> 
> 是会有些随机ip会被重定向到 CN，但是又是美国ip来的，不知道怎么回事

**Comment by tutianyu101** [comment]
> > > 
> > 
> > 
> > 大佬我还发现个问题，我按教程自建聊天室后，在cloud那边的日志发现还真的会连cn的bing
> 
> 是会有些随机ip会被重定向到 CN，但是又是美国ip来的，不知道怎么回事

大佬你的甲骨文小鸡为什么没有这个毛病啊？您能不能帮我看看nginx配置吗？

**Comment by tutianyu101** [comment]
> > > 
> > 
> > 
> > 大佬我还发现个问题，我按教程自建聊天室后，在cloud那边的日志发现还真的会连cn的bing
> 
> 是会有些随机ip会被重定向到 CN，但是又是美国ip来的，不知道怎么回事

群里讨论了下好像都有这个毛病，部署在国内的样本少还不太清楚

**Comment by tutianyu101** [comment]
The FetchEvent for "https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b" resulted in a network error response: the promise was rejected.
Promise.then (async)
(anonymous) @ workbox-118fddf1.js:1
workbox-118fddf1.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b","error":{}}]
    at H.P (https://bing.cnvvg.com/web/workbox-118fddf1.js:1:19767)
    at async H.T (https://bing.cnvvg.com/web/workbox-118fddf1.js:1:12961)
P @ workbox-118fddf1.js:1
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
index.html:34     GET https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b net::ERR_FAILED
(anonymous) @ index.html:34
(anonymous) @ index.html:35
DevTools failed to load source map: Could not load content for https://bing.cnvvg.com/rp/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index-04c94bf5.js:1250 开始第 1 次重试创建会话ID
index-04c94bf5.js:1250 开始第 2 次重试创建会话ID
index-04c94bf5.js:1250 开始第 3 次重试创建会话ID
index-04c94bf5.js:1250 开始第 4 次重试创建会话ID
index-04c94bf5.js:1250 开始第 5 次重试创建会话ID
index-04c94bf5.js:1250 开始第 6 次重试创建会话ID
index-04c94bf5.js:1250 开始第 7 次重试创建会话ID
index-04c94bf5.js:1250 开始第 8 次重试创建会话ID
index-04c94bf5.js:1250 开始第 9 次重试创建会话ID
index-04c94bf5.js:1250 开始第 10 次重试创建会话ID
index-04c94bf5.js:1250 已重试 10 次，自动创建停止

**Comment by tutianyu101** [comment]
这是正常的代码：


The FetchEvent for "https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b" resulted in a network error response: the promise was rejected.
Promise.then (async)
(anonymous) @ workbox-118fddf1.js:1
workbox-118fddf1.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b","error":{}}]
    at H.P (https://ai.cnvvg.com/web/workbox-118fddf1.js:1:19767)
    at async H.T (https://ai.cnvvg.com/web/workbox-118fddf1.js:1:12961)
P @ workbox-118fddf1.js:1
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
(index):34     GET https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b net::ERR_FAILED
(anonymous) @ (index):34
(anonymous) @ (index):35
DevTools failed to load source map: Could not load content for https://ai.cnvvg.com/rp/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index-04c94bf5.js:1250 成功创建会话ID :  51D|BingProdUnAuthenticatedUsers|57A9E947AF8CE321213BD1B6E92C605727E811F4055C968FFF35C3899CCC9F47

**Comment by tutianyu101** [comment]
> The FetchEvent for "https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b" resulted in a network error response: the promise was rejected. Promise.then (async) (anonymous) @ workbox-118fddf1.js:1 workbox-118fddf1.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b","error":{}}] at H.P (https://bing.cnvvg.com/web/workbox-118fddf1.js:1:19767) at async H.T (https://bing.cnvvg.com/web/workbox-118fddf1.js:1:12961) P @ workbox-118fddf1.js:1 DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND index.html:34 GET https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b net::ERR_FAILED (anonymous) @ index.html:34 (anonymous) @ index.html:35 DevTools failed to load source map: Could not load content for https://bing.cnvvg.com/rp/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE index-04c94bf5.js:1250 开始第 1 次重试创建会话ID index-04c94bf5.js:1250 开始第 2 次重试创建会话ID index-04c94bf5.js:1250 开始第 3 次重试创建会话ID index-04c94bf5.js:1250 开始第 4 次重试创建会话ID index-04c94bf5.js:1250 开始第 5 次重试创建会话ID index-04c94bf5.js:1250 开始第 6 次重试创建会话ID index-04c94bf5.js:1250 开始第 7 次重试创建会话ID index-04c94bf5.js:1250 开始第 8 次重试创建会话ID index-04c94bf5.js:1250 开始第 9 次重试创建会话ID index-04c94bf5.js:1250 开始第 10 次重试创建会话ID index-04c94bf5.js:1250 已重试 10 次，自动创建停止




这个和上面那台是同一台，自我恢复后的代码提示



DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
The FetchEvent for "https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b" resulted in a network error response: the promise was rejected.
Promise.then (async)
(anonymous) @ workbox-118fddf1.js:1
workbox-118fddf1.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b","error":{}}]
    at H.P (https://bing.cnvvg.com/web/workbox-118fddf1.js:1:19767)
    at async H.T (https://bing.cnvvg.com/web/workbox-118fddf1.js:1:12961)
P @ workbox-118fddf1.js:1
index.html:34     GET https://hm.baidu.com/hm.js?299c614daa53fbcede70f2d22df0a31b net::ERR_FAILED
(anonymous) @ index.html:34
(anonymous) @ index.html:35
DevTools failed to load source map: Could not load content for https://bing.cnvvg.com/rp/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
index-04c94bf5.js:1250 成功创建会话ID :  51D|BingProdUnAuthenticatedUsers|3347D27884F87E630A10E061D97DDB9C81FA35EBE78B55E0986149531B63644A

**Comment by adams549659584** [comment]
我的也会出现重定向到CN的，暂时没好的解决方案，重试创建会话ID这个不清楚怎么回事

**Comment by tutianyu101** [comment]
> 我的也会出现重定向到CN的，暂时没好的解决方案，重试创建会话ID这个不清楚怎么回事

大佬一键部署的也会出现会话id创建失败

**Comment by adams549659584** [comment]
> > 我的也会出现重定向到CN的，暂时没好的解决方案，重试创建会话ID这个不清楚怎么回事
> 
> 大佬一键部署的也会出现会话id创建失败

是会偶尔出现的，不稳定，所以加了10次重试

**Comment by tutianyu101** [comment]
> > > 我的也会出现重定向到CN的，暂时没好的解决方案，重试创建会话ID这个不清楚怎么回事
> > 
> > 
> > 大佬一键部署的也会出现会话id创建失败
> 
> 是会偶尔出现的，不稳定，所以加了10次重试

大佬可以改成1000次重试吗？间隔可以长一点

**Comment by adams549659584** [comment]
> > > > 我的也会出现重定向到CN的，暂时没好的解决方案，重试创建会话ID这个不清楚怎么回事
> > > 
> > > 
> > > 大佬一键部署的也会出现会话id创建失败
> > 
> > 
> > 是会偶尔出现的，不稳定，所以加了10次重试
> 
> 大佬可以改成1000次重试吗？间隔可以长一点

意义不大，10次都不可以的话，再多也只是增加服务器负担吧

**Comment by tutianyu101** [comment]
> > > > > 我的也会出现重定向到CN的，暂时没好的解决方案，重试创建会话ID这个不清楚怎么回事
> > > > 
> > > > 
> > > > 大佬一键部署的也会出现会话id创建失败
> > > 
> > > 
> > > 是会偶尔出现的，不稳定，所以加了10次重试
> > 
> > 
> > 大佬可以改成1000次重试吗？间隔可以长一点
> 
> 意义不大，10次都不可以的话，再多也只是增加服务器负担吧
那大佬，能不能告诉我这个会话id创建是怎么创建的？我发现你的演示站也会创建失败。我想用工具监控下，感觉很奇怪

**Comment by tutianyu101** [comment]
那大佬，能不能告诉我这个会话id创建是怎么创建的？我发现你的演示站也会创建失败。我想用工具监控下，感觉很奇怪

**Comment by tutianyu101** [comment]
> > > > > 我的也会出现重定向到CN的，暂时没好的解决方案，重试创建会话ID这个不清楚怎么回事
> > > > 
> > > > 
> > > > 大佬一键部署的也会出现会话id创建失败
> > > 
> > > 
> > > 是会偶尔出现的，不稳定，所以加了10次重试
> > 
> > 
> > 大佬可以改成1000次重试吗？间隔可以长一点
> 
> 意义不大，10次都不可以的话，再多也只是增加服务器负担吧

你的粉丝群里，我们讨论了下说会不会是微软故意的

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/54312e7c-0864-4b0a-aec0-ec6d1ef9d2e4)
微软的脚本发起的，里面挺多判断的

**Comment by tutianyu101** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/241849456-54312e7c-0864-4b0a-aec0-ec6d1ef9d2e4.png) 微软的脚本发起的，里面挺多判断的

目前发现越靠近美国的地方越不容易会话id创建失败总体概率 香港服务器＞韩国服务器＞东京服务器＞美国服务器，我昨天买的美国服务器到现在都没出现过会话id创建失败，今天在你的演示站上面发现也会创建失败，有点费解，大佬你的演示站是美国的服务器吧？

**Comment by adams549659584** [comment]
我的是日本甲骨文的

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/15f7ecae-51ff-4f8e-b5e5-1136984fadab)
看了下，未登录是会有创建失败一次，提示一定要登录，第二次就可以了，可能微软改策略了

**Comment by tutianyu101** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/241850424-15f7ecae-51ff-4f8e-b5e5-1136984fadab.png) 看了下，未登录是会有创建失败一次，提示一定要登录，第二次就可以了，可能微软改策略了

大佬这个可以绕过吗？
